### ISSUE TITLE
Add random suggestion capability

### ISSUE THREAD

**Issue by jagori** [glenwinters/gvobot#11]
If the bot can look up a webpage or integrate with other APIs, it could be useful to get it to offer suggestions. Things like:

- a random song (taken from a list somewhere? dunno where that could come from)
- a random recipe (if a webpage has a list of recipes, just randomly pick one of them and give the URL)
- a random number or letter in a certain range

**Comment by glenwinters** [comment]
Yes, all of the these are doable. The bot could do API calls to a data source or even scrape a webpage if we wanted to get fancy.

**Comment by glenwinters** [comment]
I added "!number" for random numbers in https://github.com/glenwinters/gvobot/commit/a3d13138402883eb513e4918f9f4ac9f8ec68e33

**Comment by glenwinters** [comment]
food2fork.com has an API that allows searching for recipes or simply returning the top rated ones. You can do 500 queries per day for free. Most of the other sites I looked at were more expensive or required scraping the website. food2fork.com responds with JSON.

http://food2fork.com/about/api

**Comment by glenwinters** [comment]
!recipe is complete as of https://github.com/glenwinters/gvobot/commit/6ca0d61f82f977b542c6c3490cb1d74f9957dd35! It picks one recipe from 30k of the top recipes on food2fork.com and responds with the title and URL.

**Comment by glenwinters** [comment]
We now have !number, !song and !recipe to fulfill your random needs. I'm going to close this issue and new random suggestions can be requested in their own issues.
