### ISSUE TITLE
gvobot S.C.I.E.N.C.E.-ifies spaces and dots

### ISSUE THREAD

**Issue by jagori** [glenwinters/gvobot#2]
gvobot does not distinguish between text and whitespace characters when inserting science dots after each character, and it also does not check to see if the character is already a dot. For example:

"testing 1... 2... 3..."

becomes

"T.E.S.T.I.N.G. .1....... .2....... .3......."

**Comment by glenwinters** [comment]
Fixed by https://github.com/glenwinters/gvobot/commit/a02becf041117c69b2356ca1d45625654eab2eb4

The bot now only sciencifies letters and also doesn't add an extra dot after a letter if one already exists.
