### ISSUE TITLE
gvobot cannot answer most important question #1

### ISSUE THREAD

**Issue by jagori** [glenwinters/gvobot#3]
When the message sent to gvobot was:

what is this?

the response was:

W.H.A.T. .I.S. .T.H.I.S.?.

I was left not knowing what this was.

**Comment by glenwinters** [comment]
Fixed in https://github.com/glenwinters/gvobot/commit/1b9bcc8c12098398ec6797082e4f7e45cb4fd69e which introduces a format for adding fixed responses
