### ISSUE TITLE
gvobot cannot answer most important question #2

### ISSUE THREAD

**Issue by jagori** [glenwinters/gvobot#4]
When the message sent to gvobot was:

should I mess around?

the response was:

S.H.O.U.L.D. .I. .M.E.S.S. .A.R.O.U.N.D.?.

I was left not knowing whether to mess around.

**Comment by glenwinters** [comment]
Fixed by https://github.com/glenwinters/gvobot/commit/e1cec1ebd19cb895417cd1efcb233fde4e62e67f
