### ISSUE TITLE
Sciencified text escapes special characters

### ISSUE THREAD

**Issue by jagori** [glenwinters/gvobot#7]
Sending the text:

@gvobot isn't that right

resulted in a response of:

@.G.V.O.B.O.T. .I.S.N.&.A.P.O.S.;.T. .T.H.A.T. .R.I.G.H.T.

**Comment by glenwinters** [comment]
Fixed by https://github.com/glenwinters/gvobot/commit/13a7d48b51c369a16cbfa1130ba1413fe471138a
